#数据源配置 - 测试环境
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: UmVkaXM6IA
    database: 0
    ssl: false
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://10.29.1.216:3306/db_atwsrm3?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
          username: root
          password: atwadmin
        #          url: jdbc:mysql://10.29.1.59:3306/db_atwsrm3?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
        #          username: db_atwsrm3
        #          password: '!6U0Ulu6hEBvYxwQ'
        oracle:
          url: jdbc:oracle:thin:@10.29.1.215:1521:atwdb
          username: atwsrm
          password: oracle
          driver-class-name: oracle.jdbc.driver.OracleDriver

blade:
  prop:
    upload-domain: http://localhost:8888
    remote-mode: true
    remote-path: /usr/share/nginx/html
    remote-path-iis: D://iis/html
    log-mode: true

atwsrm:
  bizapiDomain: http://atwsrm.bizapi.test.antiwearvalve.com
  u9ApiDomain: http://10.29.1.127:8081/WG_APITest
  esbApiDomain: http://10.29.1.138:8097
  sqsApiDomain: http://10.29.1.138:8097
  mesApiDomain: http://10.29.1.127/MESTest_API
  bizapiUrl: http://atwsrm.bizapi.test.antiwearvalve.com

#邮件发送领料扣账
WWEMAILS:
  FROM:
    srm3@atwwg.api.antiwearvalve.cn
  TO:
    zhouliangwei@antiwearvalve.com
  CC:
    zhouliangwei@antiwearvalve.com
  CG:
    zhouliangwei@antiwearvalve.com
  PriceTO:
    jijunkang@antiwearvalve.com
  PriceCC:
    jijunkang@antiwearvalve.com

#模板默认路径
model:
  modelPath:
    /www/wwwjava/srm-admin-api/modelFiles/送货计划表_模板.xlsx
  outputPath:
    /www/wwwjava/srm-admin-api/outputFiles/

#sendCloud默认配置
sendCloud:
  url:
    http://api.sendcloud.net/apiv2/mail/send
  apiUser:
    atwwg_single_sender_dev
  apiKey:
    ALArOxO9xe6KVlq6
  splitSymbol:
    /
